package com.wecho.core.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Table(name = "article")
public class Article implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_name
     *
     * @mbggenerated
     */
    private String articleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_address
     *
     * @mbggenerated
     */
    private String articleAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_author
     *
     * @mbggenerated
     */
    private String articleAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_keyword
     *
     * @mbggenerated
     */
    private String articleKeyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_flag
     *
     * @mbggenerated
     */
    private String articleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_style
     *
     * @mbggenerated
     */
    private String articleStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_create_at
     *
     * @mbggenerated
     */
    private Date articleCreateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.valid_flag
     *
     * @mbggenerated
     */
    @JsonIgnore
    private String validFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_name
     *
     * @return the value of article.article_name
     *
     * @mbggenerated
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_name
     *
     * @param articleName the value for article.article_name
     *
     * @mbggenerated
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_address
     *
     * @return the value of article.article_address
     *
     * @mbggenerated
     */
    public String getArticleAddress() {
        return articleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_address
     *
     * @param articleAddress the value for article.article_address
     *
     * @mbggenerated
     */
    public void setArticleAddress(String articleAddress) {
        this.articleAddress = articleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_author
     *
     * @return the value of article.article_author
     *
     * @mbggenerated
     */
    public String getArticleAuthor() {
        return articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_author
     *
     * @param articleAuthor the value for article.article_author
     *
     * @mbggenerated
     */
    public void setArticleAuthor(String articleAuthor) {
        this.articleAuthor = articleAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_keyword
     *
     * @return the value of article.article_keyword
     *
     * @mbggenerated
     */
    public String getArticleKeyword() {
        return articleKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_keyword
     *
     * @param articleKeyword the value for article.article_keyword
     *
     * @mbggenerated
     */
    public void setArticleKeyword(String articleKeyword) {
        this.articleKeyword = articleKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_flag
     *
     * @return the value of article.article_flag
     *
     * @mbggenerated
     */
    public String getArticleFlag() {
        return articleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_flag
     *
     * @param articleFlag the value for article.article_flag
     *
     * @mbggenerated
     */
    public void setArticleFlag(String articleFlag) {
        this.articleFlag = articleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_style
     *
     * @return the value of article.article_style
     *
     * @mbggenerated
     */
    public String getArticleStyle() {
        return articleStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_style
     *
     * @param articleStyle the value for article.article_style
     *
     * @mbggenerated
     */
    public void setArticleStyle(String articleStyle) {
        this.articleStyle = articleStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_create_at
     *
     * @return the value of article.article_create_at
     *
     * @mbggenerated
     */
    public Date getArticleCreateAt() {
        return articleCreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_create_at
     *
     * @param articleCreateAt the value for article.article_create_at
     *
     * @mbggenerated
     */
    public void setArticleCreateAt(Date articleCreateAt) {
        this.articleCreateAt = articleCreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.mark
     *
     * @return the value of article.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.mark
     *
     * @param mark the value for article.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.valid_flag
     *
     * @return the value of article.valid_flag
     *
     * @mbggenerated
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.valid_flag
     *
     * @param validFlag the value for article.valid_flag
     *
     * @mbggenerated
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag;
    }
}